---
all:
  vars:
    ansible_user: root
    ensure_keys_for: [root]

    ensure_hostname: true
    ensure_hosts: true

    unattend_disable: true
    update_pkg_cache: true
    features:
      evpn: false

    one_version: '6.10'
    one_pass: 'opennebula'
    one_token: 'ci:Pantufl4.'
    db_backend: SQLite


frontend:
  hosts:
    fe: { ansible_host: 85.215.135.141 }
  vars:
    vn:
      vxlan:
        managed: true
        template:
          VN_MAD: vxlan
          PHYDEV: ens6
          BRIDGE: br1
          VLAN_ID: 86
          FILTER_IP_SPOOFING: 'NO'
          FILTER_MAC_SPOOFING: 'NO'
          GUEST_MTU: 1450
          AR:
            TYPE: IP4
            IP: 217.154.201.90
            SIZE: 1
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 217.154.201.1

node:
  hosts:
    host01: { ansible_host: 217.154.88.115 }
  vars:
    vn:
      vxlan:
        managed: true
        template:
          VN_MAD: vxlan
          PHYDEV: ens6
          BRIDGE: br1
          VLAN_ID: 86
          FILTER_IP_SPOOFING: 'NO'
          FILTER_MAC_SPOOFING: 'NO'
          GUEST_MTU: 1450
          AR:
            TYPE: IP4
            IP: 217.154.201.90
            SIZE: 1
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 217.154.201.1
