---
all:
  vars:
    ansible_user: root
    ensure_keys_for: [root]

    ensure_hostname: true
    ensure_hosts: true

    unattend_disable: true
    update_pkg_cache: true
    features:
      evpn: false

    one_version: '6.10'
    one_pass: 'opennebula'
    one_token: 'ci:Pantufl4.'
    db_backend: SQLite
    vn:
      pubridge:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: ens6
          BRIDGE: br0
          AR:
            TYPE: IP4
            IP: 217.154.225.193
            SIZE: 1
          DNS: 1.1.1.1
          NETWORK_MASK: 255.255.255.255
          GATEWAY: 192.168.1.2
          FILTER_IP_SPOOFING: 'NO'
          FILTER_MAC_SPOOFING: 'NO'
      vxlan:
        managed: true
        template:
          VN_MAD: vxlan
          PHYDEV: ens7
          BRIDGE: br1
          VLAN_ID: 86
          FILTER_IP_SPOOFING: 'NO'
          FILTER_MAC_SPOOFING: 'NO'
          GUEST_MTU: 1450
          AR:
            TYPE: IP4
            IP: 10.1.2.100
            SIZE: 48
          NETWORK_ADDRESS: 10.1.2.0
          NETWORK_MASK: 255.255.255.0
    ionos_config:
      data_center_uuid: "7ff493e4-c722-4429-80f3-0c90564c26c3"
      public_bridge_name: "br0"
    ionosctl:
      install_path: "${HOME}/ionosctl/"
      version: "6.8.4"
      # The token file shall be placed in 'playbooks/files/' directory
      token: "{{ lookup('file', '.ionosctl_token') }}"

frontend:
  hosts:
    fe: { ansible_host: 217.154.225.208 }

node:
  hosts:
    host01: { ansible_host: 217.154.225.208 }
    host02: { ansible_host: 217.154.225.209 }