---
all:
  vars:
    ansible_user: root
    ensure_keys_for: [root]

    ensure_hostname: true
    ensure_hosts: true

    unattend_disable: true
    update_pkg_cache: true
    features:
      evpn: false

    one_version: '6.10'
    one_pass: 'opennebula'
    one_token: 'ci:Pantufl4.'
    db_backend: SQLite


frontend:
  hosts:
    fe: { ansible_host: 85.215.135.141 }
  vars:
    vn:
      bridge:
        managed: true
        template:
          VN_MAD: bridge
          AR:
            TYPE: IP4
            IP: 10.11.12.200
            SIZE: 48
          NETWORK_ADDRESS: 10.11.12.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 10.11.12.1
          DNS: 1.1.1.1
      vxlan:
        managed: true
        template:
          VN_MAD: vxlan
          PHYDEV: ens6
          BRIDGE: br1
          VLAN_ID: 86
          FILTER_IP_SPOOFING: 'NO'
          FILTER_MAC_SPOOFING: 'YES'
          GUEST_MTU: 1450
          AR:
            TYPE: IP4
            IP: 192.168.150.200
            SIZE: 48
          NETWORK_ADDRESS: 192.168.150.0
          NETWORK_MASK: 255.255.255.0

node:
  hosts:
    host01: { ansible_host: 217.154.88.115 }
  vars:
    vn:
      vxlan:
        # Define a VNET of type vxlan and move IP4/6 settings from ens6 to br1.
        managed: true
        template:
          VN_MAD: vxlan
          PHYDEV: ens6
          BRIDGE: br1
          VLAN_ID: 86
          FILTER_IP_SPOOFING: 'NO'
          FILTER_MAC_SPOOFING: 'YES'
          GUEST_MTU: 1450
          AR:
            TYPE: IP4
            IP: 192.168.150.200
            SIZE: 48
          NETWORK_ADDRESS: 192.168.150.0
          NETWORK_MASK: 255.255.255.0
