---
- name: Gather facts explicitly
  setup:
  when: ansible_system is not defined or ansible_architecture is not defined

- name: Determine OS type for download (from remote host)
  set_fact:
    os_type: "{% if ansible_system == 'Linux' %}linux{% elif ansible_system == 'Darwin' %}darwin{% else %}linux{% endif %}"

- name: Determine architecture for download (from remote host)
  set_fact:
    arch_type: "{% if ansible_architecture == 'x86_64' %}amd64{% elif ansible_architecture == 'aarch64' %}arm64{% elif ansible_architecture in ['i386', 'i686'] %}386{% else %}amd64{% endif %}"

- block:

  - name: Set download URL
    set_fact:
      ionosctl_url: "https://github.com/ionos-cloud/ionosctl/releases/download/v{{ ionosctl.version }}/ionosctl-{{ ionosctl.version }}-{{ os_type }}-{{ arch_type }}.tar.gz"

  - name: Create temporary directory for download
    file:
      path: "/tmp/ionosctl-{{ ionosctl.version }}"
      state: directory
      mode: '0755'

  - name: Download and extract ionosctl
    shell: >
      curl -sL {{ ionosctl_url }} | tar -xzv -C /tmp/ionosctl-{{ ionosctl.version }}
    args:
      creates: "/tmp/ionosctl-{{ ionosctl.version }}/ionosctl"
    no_log: true

  - name: Ensure ionosctl install path exists
    file:
      path: "{{ ionosctl.install_path | regex_replace('/$', '')}}"
      state: directory
      mode: '0755'
      owner: oneadmin
      group: oneadmin

  - name: Move ionosctl binary to system path
    copy:
      src: "/tmp/ionosctl-{{ ionosctl.version }}/ionosctl"
      dest: "{{ ionosctl.install_path | regex_replace('/$', '') }}/ionosctl"
      mode: '0755'
      remote_src: yes
      owner: oneadmin
      group: oneadmin

  - name: Clean up temporary directory
    file:
      path: "/tmp/ionosctl-{{ ionosctl.version }}"
      state: absent

  - name: Verify ionosctl installation
    command: "{{ ionosctl.install_path | regex_replace('/$', '') }}/ionosctl version"
    register: ionosctl_version_check
    changed_when: false

  - name: Add ionosctl to oneadmin's PATH permanently
    lineinfile:
      path: "~/.bashrc"
      line: "export PATH={{ ionosctl.install_path | regex_replace('/$', '') }}:$PATH"
      regexp: "^export PATH=.*{{ ionosctl.install_path | regex_replace('/$', '') }}.*$"
      state: present
      create: yes

  - name: Testing login with ionosctl
    ansible.builtin.shell: |
      source ~/.bashrc
      ionosctl login --force --token '{{ ionosctl.token }}'
    register: ionosctl_login
    args:
      executable: /bin/bash
    ignore_errors: true
    no_log: true

  - name: Fail with message if ionosctl login failed
    ansible.builtin.fail:
      msg: |
        ionosctl login failed with code {{ ionosctl_login.rc }}.
        Output:
        {{ ionosctl_login.stdout | default('') }}
        Error:
        {{ ionosctl_login.stderr | default('') }}
        Try to log in manually using: ionosctl login --force --token 'YOUR_TOKEN'
    when: ionosctl_login.rc != 0

  - name: Logout from ionosctl
    ansible.builtin.shell: |
      source ~/.bashrc
      ionosctl logout
    args:
      executable: /bin/bash

  become: true
  become_user: oneadmin

- name: Show installed ionosctl version
  debug:
    msg: "Installed ionosctl: {{ ionosctl_version_check.stdout }}"
