---
- name: Gather facts explicitly
  setup:
  when: ansible_system is not defined or ansible_architecture is not defined

- name: Determine OS type for download (from remote host)
  set_fact:
    os_type: "{% if ansible_system == 'Linux' %}linux{% elif ansible_system == 'Darwin' %}darwin{% else %}linux{% endif %}"

- name: Determine architecture for download (from remote host)
  set_fact:
    arch_type: "{% if ansible_architecture == 'x86_64' %}amd64{% elif ansible_architecture == 'aarch64' %}arm64{% elif ansible_architecture in ['i386', 'i686'] %}386{% else %}amd64{% endif %}"

- block:

  - name: Set download URL
    set_fact:
      ionosctl_url: "https://github.com/ionos-cloud/ionosctl/releases/download/v{{ ionos_config.ionosctl.version }}/ionosctl-{{ ionos_config.ionosctl.version }}-{{ os_type }}-{{ arch_type }}.tar.gz"

  - name: Create temporary directory for download
    file:
      path: "/tmp/ionosctl-{{ ionos_config.ionosctl.version }}"
      state: directory
      mode: '0755'

  - name: Download and extract ionosctl
    shell: >
      curl -sL {{ ionosctl_url }} | tar -xzv -C /tmp/ionosctl-{{ ionos_config.ionosctl.version }}
    args:
      creates: "/tmp/ionosctl-{{ ionos_config.ionosctl.version }}/ionosctl"
    no_log: true

  - name: Ensure ionosctl install path exists
    file:
      path: "{{ ionos_config.ionosctl.install_path | regex_replace('/$', '')}}"
      state: directory
      mode: '0755'
      owner: oneadmin
      group: oneadmin

  - name: Move ionosctl binary to system path
    copy:
      src: "/tmp/ionosctl-{{ ionos_config.ionosctl.version }}/ionosctl"
      dest: "{{ ionos_config.ionosctl.install_path | regex_replace('/$', '') }}/ionosctl"
      mode: '0755'
      remote_src: yes
      owner: oneadmin
      group: oneadmin

  - name: Clean up temporary directory
    file:
      path: "/tmp/ionosctl-{{ ionos_config.ionosctl.version }}"
      state: absent

  - name: Verify ionosctl installation
    command: "{{ ionos_config.ionosctl.install_path | regex_replace('/$', '') }}/ionosctl version"
    register: ionosctl_version_check
    changed_when: false

  - name: Add ionosctl to oneadmin's PATH permanently
    lineinfile:
      path: "~/.bashrc"
      line: "export PATH={{ ionos_config.ionosctl.install_path | regex_replace('/$', '') }}:$PATH"
      regexp: "^export PATH=.*{{ ionos_config.ionosctl.install_path | regex_replace('/$', '') }}.*$"
      state: present
      create: yes

  become: true
  become_user: oneadmin

- name: Show installed ionosctl version
  debug:
    msg: "Installed ionosctl: {{ ionosctl_version_check.stdout }}"
